// Exercise every tool over stdio. Makes ~6 Apple calls (paced ~3 s apart).
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
const c = new Client({ name: 'smoke', version: '0' });
await c.connect(new StdioClientTransport({ command: 'node', args: [new URL('../dist/index.js', import.meta.url).pathname] }));
const tools = await c.listTools();
console.log('TOOLS:', tools.tools.map(t => t.name).join(', '));
const show = (name, r, n = 900) => { const t = r.content[0].text; console.log(`\n== ${name}${r.isError ? ' (ERROR)' : ''}\n` + t.slice(0, n)); return t; };
const call = (name, args = {}) => c.callTool({ name, arguments: args });
show('altis_status', await call('altis_status'));
show('altis_list_apps', await call('altis_list_apps'), 400);
show('altis_list_keywords', await call('altis_list_keywords', { appId: 2, rankedOnly: true, orderBy: 'lastPosition', limit: 2, includeMetrics: true }), 1600);
show('altis_get_keyword', await call('altis_get_keyword', { text: 'plate calculator', countryCode: 'US', includeMetrics: true }), 1800);
show('metadata_check', await call('metadata_check', { title: 'LoadPR: Plate Calculator & 1RM', subtitle: 'Barbell Math & Wendler 531 Log', keywords: 'one,rep,max,calc,chart,app,loader,loading,weight,lifting,powerlifting,strength,squat,deadlift,bench', trackedKeywords: ['bench press calculator', 'lift percentage calculator', 'plate calculator'] }), 600);
show('altis_add_keywords dryRun', await call('altis_add_keywords', { appId: 2, keywords: ['plate calculator', 'zzz smoke test'], dryRun: true }));
show('altis_delete_keywords dryRun', await call('altis_delete_keywords', { appId: 2, keywords: ['zzz not there'], dryRun: true }));
show('appstore_suggestions', await call('appstore_suggestions', { term: 'plate calc' }), 1400);
show('appstore_search+target', await call('appstore_search', { term: 'plate calculator', limit: 200, targetAppId: '6768525538' }), 300);
show('appstore_check_rank', await call('appstore_check_rank', { term: '1rm calculator', appId: '6768525538' }), 1200);
show('appstore_check_rank_batch', await call('appstore_check_rank_batch', { terms: ['1rm calculator', 'plate calculator'], appId: '6768525538' }), 700);
show('screen_results', await call('screen_results', { appId: '6768525538', limit: 5 }), 700);
show('screen_history', await call('screen_history', { term: '1rm calculator' }), 400);
show('screen expandOnly', await call('screen', { seeds: ['plate'], appId: '6768525538', suffixes: ['', 'c'], expandOnly: true }), 900);
show('rate_status', await call('rate_status'));
show('screen_store_status', await call('screen_store_status'));
await c.close();
